language: groovy

branches:
  only:
    - master

before_install:
 - sudo add-apt-repository -y ppa:groovy-dev/grails
 - sudo apt-get -y update
 - sudo apt-get -y install grails-ppa
 - sudo apt-get -y install grails 2.0.2
 
script: grails war