apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terroir-tracking-web
  description: Find where your juice comes from
  tags:
    - go
    - website
spec:
  type: website
  lifecycle: production
  owner: app-invoice/blue-team
